sudo: required
language: python
services:
  - docker
before_install:
  - docker build -t cloudpassage_halo_python_sdk .
script:
  - ./travis.sh
notifications:
  email:
    recipients:
      - toolbox@cloudpassage.com
    on_success: never
    on_failure: always